name: Python Version Compatibility Check

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

#      - name: Add Package source
#        run: sudo add-apt-repository ppa:deadsnakes/ppa -y
#      
#      - name: Install Python
#        run: sudo apt update && sudo apt install python3.11-full -y

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          check-latest: true
       
      - name: Install Dependencies
        run: pip3 install -r requirements.txt

